version: "3"

services:
  database:
    image: "postgres:13"
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
